version: '1.0'
name: pipeline-20220802
displayName: pipeline-20220802
triggers:
  trigger: auto
  push:
    tags:
      prefix:
        - v
stages:
  - name: stage-c1981a39
    displayName: 应用构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 执行编译命令'
          - npm install && npm run dist
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-77339120
    displayName: 应用发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
