name: Build and release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Npm Install
        run: npm install

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenBlockDesktop-win-x64.exe
          path: dist/OpenBlock*Setup.exe
          retention-days: 1