name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache nodemodules
        uses: actions/cache@v1
        env:
            cache-name: desktop-dependencies
        with:
            # 需要缓存的文件的路径
            path: ./node_modules 
            # 对缓存的文件指定的唯一标识
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }} 
            # 用于没有再找目标key的缓存的backup选项
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-

      - name: Npm Install
        run: npm install

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DBit+-win-x64.exe
          path: dist/DBit+*Setup.exe
          retention-days: 1
 
  create-release:
    needs: [build-windows]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: DBit+ Desktop ${{ steps.tag.outputs.tag }}
          body: |
            - **New feature**
              1. First Change
              2. Second Change

            - **Fix bug**
              1. First Change
              2. Second Change
          draft: true
          prerelease: false

      - name: Download all build result
        uses: actions/download-artifact@v2

      # # Windows x64 Release
      # - name: Zip win x64 file
      #   uses: papeloto/action-zip@v1
      #   with:
      #       files: DBit+-win-x64.exe
      #       dest: DBit+-win-x64.zip

      - uses: edgarrc/action-7z@v1
        with:
          # args: 7z a -t7z -mx=9 DBit+-${{ steps.package-version.outputs.current-version }}-win-x64.7z ./DBit+-win-x64.exe
          args: 7z a -mx -myx -mmt=off -ms=on -mtm=off -mtc=off -mta=off -mtr=off -m0=LZMA:d=384m:fb=273:lc=8 -mmc=1000000000 DBit+-${{ steps.package-version.outputs.current-version }}-win-x64.7z ./DBit+-win-x64.exe

      - name: Relase Windows x64 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # asset_path: ./DBit+-win-x64.zip
          asset_path: DBit+-${{ steps.package-version.outputs.current-version }}-win-x64.7z
          # asset_name: DBit+-${{ steps.package-version.outputs.current-version }}-win-x64.zip
          asset_name: DBit+-${{ steps.package-version.outputs.current-version }}-win-x64.zip
          asset_content_type: application/zip

      # Checksum Release
      - name: Checksum
        run: sha256sum DBit+-*.zip >> checksums.txt

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: checksums.txt
          asset_name: ${{ steps.package-version.outputs.current-version }}-checksums-sha256.txt
          asset_content_type: application/zip


      - name: Install coscmd
        run: sudo pip install coscmd

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.TCOSSecretId }}
          SECRET_KEY: ${{ secrets.TCOSSecretKey }}
          BUCKET: dilemu-1253248162
          REGION: ap-beijing
        # run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -e dilemu-1253248162.cos.accelerate.myqcloud.com
        
      - name: Upload tencent cos
        run: coscmd upload ./DBit+-${{ steps.package-version.outputs.current-version }}-win-x64.7z /